name: Deploy to skak.dev

#on:
#  push:
#    branches: 
#      - release
on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: "skak.dev"
        username: ${{secrets.DEPLOY_USERNAME}}
        key: ${{secrets.DEPLOY_KEY}}
        passphrase: ${{secrets.DEPLOY_PASSPHRASE}}
        port: ${{secrets.DEPLOY_PORT}}
        script_stop: true
        script: |
          cd /var/www/ParallelChess
          git checkout release
          cd /var/www/ParallelChess/ChessDisplay
          ng run build-prod
          cd /var/www/ParallelChess/ChessApi
          supervisorctl stop all
          dotnet publish --configuration Release
          supervisorctl start all
      
