name: .NET Core

on:
  push:
    branches: 
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.
      with:
        host: ${{secrets.DEPLOY_HOST}}
        username: ${{secrets.DEPLOY_USERNAME}}
        key: ${{secrets.DEPLOY_KEY}}
        passphrase: ${{secrets.DEPLOY_PASSPHRASE}}
        port: ${{secrets.DEPLOY_PORT}}
        script_stop: true
        script: |
          cd /var/www/ParallelChess
          git checkout release
          cd /var/www/ParallelChess/ChessDisplay
          ng run build-prod
          cd /var/www/ParallelChess/ChessApi
          supervisorctl stop all
          dotnet publish --configuration Release
          supervisorctl start all
      
