name: Deploy to skak.dev

on:
  push:
    branches: 
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: run tests
      run: dotnet test --configuration Release
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: "165.22.88.133"
        username: ${{secrets.DEPLOY_USERNAME}}
        key: ${{secrets.DEPLOY_KEY}}
        passphrase: ${{secrets.DEPLOY_PASSPHRASE}}
        port: "22"
        script_stop: true
        script: |
          cd /var/www/ParallelChess
          git fetch
          git checkout release
          git pull
          cd /var/www/ParallelChess/ChessDisplay
          npm install --production
          npm run build-prod
          cd /var/www/ParallelChess/ChessApi
          supervisorctl stop all
          dotnet publish --configuration Release
          supervisorctl start all
      
